/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/warehousecompressed2.glb --types 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFAction = THREE.AnimationClip;

type GLTFResult = GLTF & {
	nodes: {
		Benda: THREE.Mesh;
		benda001: THREE.Mesh;
		benda002: THREE.Mesh;
		benda003: THREE.Mesh;
		building: THREE.Mesh;
		door: THREE.Mesh;
		floor: THREE.Mesh;
		LeftRack: THREE.Mesh;
		material: THREE.Mesh;
		Material2001: THREE.Mesh;
		Material2002: THREE.Mesh;
		Material3: THREE.Mesh;
		Material3001: THREE.Mesh;
		MIddleRack: THREE.Mesh;
		Right2Rack: THREE.Mesh;
		RightRack: THREE.Mesh;
		roof: THREE.Mesh;
		wall: THREE.Mesh;
		window2: THREE.Mesh;
	};
	materials: {
		["window.003"]: THREE.MeshStandardMaterial;
		["Metal21-basecolor.003"]: THREE.MeshStandardMaterial;
		["Blackout.003"]: THREE.MeshStandardMaterial;
		["Metal.003"]: THREE.MeshStandardMaterial;
		["Floor.003"]: THREE.MeshStandardMaterial;
		["Wood05-basecolor.003"]: THREE.MeshStandardMaterial;
		["material.003"]: THREE.MeshStandardMaterial;
		["material_0.003"]: THREE.MeshStandardMaterial;
		["Light.003"]: THREE.MeshStandardMaterial;
		["Ceiling.003"]: THREE.MeshStandardMaterial;
		["Wall.003"]: THREE.MeshStandardMaterial;
	};
	animations: GLTFAction[];
};

export function Model(props: React.JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF(
		"/warehousecompressed2.glb",
	) as unknown as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<mesh
					geometry={nodes.Benda.geometry}
					material={materials["window.003"]}
					position={[103.636, 114.814, 68.844]}
					scale={50.278}
				/>
				<mesh
					geometry={nodes.benda001.geometry}
					material={materials["Metal21-basecolor.003"]}
					position={[38.753, 93.804, 48]}
					scale={48}
				/>
				<mesh
					geometry={nodes.benda002.geometry}
					material={materials["Metal21-basecolor.003"]}
					position={[38.753, 94.014, 48]}
					scale={48}
				/>
				<mesh
					geometry={nodes.benda003.geometry}
					material={materials["Metal21-basecolor.003"]}
					position={[64.316, 79.74, 48]}
					scale={48}
				/>
				<mesh
					geometry={nodes.building.geometry}
					material={materials["Blackout.003"]}
					position={[-5.298, -17.936, 96.344]}
					scale={279}
				/>
				<mesh
					geometry={nodes.door.geometry}
					material={materials["Metal.003"]}
					position={[-19.472, 108.627, 40.104]}
					scale={39.896}
				/>
				<mesh
					geometry={nodes.floor.geometry}
					material={materials["Floor.003"]}
					position={[-5.298, -19.998, 0]}
					scale={274}
				/>
				<mesh
					geometry={nodes.LeftRack.geometry}
					material={materials["Wood05-basecolor.003"]}
					position={[-155.439, 75.201, 74.032]}
					scale={68.031}
				/>
				<mesh
					geometry={nodes.material.geometry}
					material={materials["Wood05-basecolor.003"]}
					position={[25.936, 76.306, 74.032]}
					scale={236.592}
				/>
				<mesh
					geometry={nodes.Material2001.geometry}
					material={materials["material.003"]}
					position={[25.936, 75.201, 73.906]}
					scale={236.842}
				/>
				<mesh
					geometry={nodes.Material2002.geometry}
					material={materials["Metal21-basecolor.003"]}
					position={[11.338, 93.775, 51.076]}
					scale={43.424}
				/>
				<mesh
					geometry={nodes.Material3.geometry}
					material={materials["material_0.003"]}
					position={[25.936, 8.606, 90.483]}
					scale={236.842}
				/>
				<mesh
					geometry={nodes.Material3001.geometry}
					material={materials["Light.003"]}
					position={[-5.298, -41.456, 174.388]}
					scale={48}
				/>
				<mesh
					geometry={nodes.MIddleRack.geometry}
					material={materials["Metal21-basecolor.003"]}
					position={[28.304, -1.128, 87.549]}
					scale={239.835}
				/>
				<mesh
					geometry={nodes.Right2Rack.geometry}
					material={materials["Metal21-basecolor.003"]}
					position={[253.829, -83.258, 48]}
					scale={48}
				/>
				<mesh
					geometry={nodes.RightRack.geometry}
					material={materials["Wood05-basecolor.003"]}
					position={[207.311, 75.201, 74.032]}
					scale={68.031}
				/>
				<mesh
					geometry={nodes.roof.geometry}
					material={materials["Ceiling.003"]}
					position={[-5.298, -20.436, 184.142]}
					scale={274}
				/>
				<mesh
					geometry={nodes.wall.geometry}
					material={materials["Wall.003"]}
					position={[-5.298, -20.436, 96.344]}
					scale={274}
				/>
				<mesh
					geometry={nodes.window2.geometry}
					material={materials["window.003"]}
					position={[274.89, -20.35, 68.844]}
					scale={50.278}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/warehousecompressed2.glb");
